glanguage: c
env: PACKAGE_NAME=niem-change-processes ZIP_FILE=tmp/${PACKAGE_NAME}-${TRAVIS_TAG}.zip
install:
- sudo apt-get --verbose-versions update
- sudo apt-get --verbose-versions remove libxdot4 libgvc5 libgraph4 libcgraph5 libcdt4
  libpathplan4
- sudo apt-get --verbose-versions install libdevil1c2 libgts-0.7-5 liblasi0 freeglut3
  libglade2-0 libgtkglext1
- curl -o libgraphviz.deb http://www.graphviz.org/pub/graphviz/stable/ubuntu/ub12.04/x86_64/libgraphviz4_2.38.0-1~precise_amd64.deb
- sudo dpkg --force-conflicts -i libgraphviz.deb
- curl -o graphviz.deb http://www.graphviz.org/pub/graphviz/stable/ubuntu/ub12.04/x86_64/graphviz_2.38.0-1~precise_amd64.deb
- sudo dpkg -i graphviz.deb
script: make ${ZIP_FILE}
notifications:
  email: true
deploy:
  provider: releases
  api_key:
    secure: IqnIJh5THI+YFOdicLNirT7nCBh+QylSvLYi0F10NKitRXJsVfI/F8ePnx/kCudgu6xeihhF5UxCjfQGxxuULzmUsIGZfEkJz8NrrGu9f0SnHo+p0laYUdy492vQnr6UDmImsztMn8tycLzQa/cn76inDN/pJkYi18gL59RLsSY=
  file: ${ZIP_FILE}
  on:
    repo: webb/niem-change-processes
    tags: true
    all_branches: true
