language: c
env: PACKAGE_NAME=niem-change-processes ZIP_FILE=${PACKAGE_NAME}-${TRAVIS_TAG}.zip
install:
  - sudo apt-get --verbose-versions update
  - sudo apt-get --verbose-versions remove libxdot4 libgvc5 libgraph4 libcgraph5 libcdt4 libpathplan4
  - sudo apt-get --verbose-versions install libdevil1c2 libgts-0.7-5 liblasi0 freeglut3 libglade2-0 libgtkglext1
  - curl -o libgraphviz.deb http://www.graphviz.org/pub/graphviz/stable/ubuntu/ub12.04/x86_64/libgraphviz4_2.38.0-1~precise_amd64.deb
  - sudo dpkg --force-conflicts -i libgraphviz.deb
  - curl -o graphviz.deb http://www.graphviz.org/pub/graphviz/stable/ubuntu/ub12.04/x86_64/graphviz_2.38.0-1~precise_amd64.deb
  - sudo dpkg -i graphviz.deb
script: make ${ZIP_FILE}
deploy:
  provider: releases
  api_key:
    secure: "tvGEUhqT4lzm1Q6QRqDyQ+ZQ/9YSjsIjJsphlC2obtvcY3NUDEm33jyIxJpBesNWgtiq6/ZOm7sBjJJV9ymo3RwrVOcNBgWBJAl4Vc0Gun5p9t9BclL9bz7fS/G/YBK+HVsNGypF47wKXCmJldl477rkts8h2Pk9KJzmhSOksTo="
  file: ${ZIP_FILE}
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
notifications:
  email: true
